# spring:
#   jpa:
#     show-sql: true
#     hibernate:
#       ddl-auto: update

#   datasource:
#     h2:
#       url: jdbc:h2:mem:h2db
#       driver-class-name: org.h2.Driver
#       username: sa
#       password:

#     postgres:
#       url: jdbc:postgresql://localhost:5432/studentdb
#       driver-class-name: org.postgresql.Driver
#       username: postgres
#       password: root
